image: rqcd/centos7.2.1511-buildtools-serialhdf5

stages:
    - build
    - test

build-job:
    stage: build
    script:
      - yum -y install sqlite-devel jsoncpp-devel
      - mkdir install
      - cmake -DCMAKE_INSTALL_PREFIX=./install -DJSONCPP_ROOT_DIR=/usr/include/jsoncpp
      - make -j 2 install
    artifacts:
        paths:
          - install/

test-job:
    stage: test
    script:
        - ./install/bin/tests
    dependencies:
        - build-job
